#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : xdg-user-dirs-gtk
Version  : 0.12
Release  : 16
URL      : https://download.gnome.org/sources/xdg-user-dirs-gtk/0.12/xdg-user-dirs-gtk-0.12.tar.xz
Source0  : https://download.gnome.org/sources/xdg-user-dirs-gtk/0.12/xdg-user-dirs-gtk-0.12.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xdg-user-dirs-gtk-bin = %{version}-%{release}
Requires: xdg-user-dirs-gtk-data = %{version}-%{release}
Requires: xdg-user-dirs-gtk-license = %{version}-%{release}
Requires: xdg-user-dirs-gtk-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : xdg-user-dirs
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
xdg-user-dirs-gtk is a companion to xdg-user-dirs that integrates it into
the Gnome desktop and Gtk+ applications.

%package bin
Summary: bin components for the xdg-user-dirs-gtk package.
Group: Binaries
Requires: xdg-user-dirs-gtk-data = %{version}-%{release}
Requires: xdg-user-dirs-gtk-license = %{version}-%{release}

%description bin
bin components for the xdg-user-dirs-gtk package.


%package data
Summary: data components for the xdg-user-dirs-gtk package.
Group: Data

%description data
data components for the xdg-user-dirs-gtk package.


%package license
Summary: license components for the xdg-user-dirs-gtk package.
Group: Default

%description license
license components for the xdg-user-dirs-gtk package.


%package locales
Summary: locales components for the xdg-user-dirs-gtk package.
Group: Default

%description locales
locales components for the xdg-user-dirs-gtk package.


%prep
%setup -q -n xdg-user-dirs-gtk-0.12
cd %{_builddir}/xdg-user-dirs-gtk-0.12
pushd ..
cp -a xdg-user-dirs-gtk-0.12 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736798356
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/xdg-user-dirs-gtk
cp %{_builddir}/xdg-user-dirs-gtk-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xdg-user-dirs-gtk/dfac199a7539a404407098a2541b9482279f690d || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang xdg-user-dirs-gtk
## install_append content
mv %{buildroot}/etc/xdg %{buildroot}/usr/share/. && rmdir %{buildroot}/etc

## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/data/applications/user-dirs-update-gtk.desktop

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xdg-user-dirs-gtk-update
/usr/bin/xdg-user-dirs-gtk-update

%files data
%defattr(-,root,root,-)
/usr/share/xdg/autostart/user-dirs-update-gtk.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdg-user-dirs-gtk/dfac199a7539a404407098a2541b9482279f690d

%files locales -f xdg-user-dirs-gtk.lang
%defattr(-,root,root,-)

